version: "3.7"
services:
  app:
    image: yayalouis123/gain_edge2
    ports:
      - '7878:7878'
    environment:
      OPERATOR_URI: operator:8787
    volumes:
      - type: volume
        source: shared
        target: /repos
  operator:
    image: harmonia/operator
    ports:
      - '9080:9080'
      - '8787:8787'
    volumes:
      - ./config.yml:/app/config.yml
      - type: volume
        source: shared
        target: /repos
volumes:
  shared:
